
apiVersion: v1
kind: Service
metadata:
  name: helloservice
spec:
  selector:
    app: hello
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5500
      targetPort: 3500
      nodePort: 31111
