
apiVersion: v1
kind: Service
metadata:
  name: worldservice
spec:
  selector:
    app: world
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5501
      targetPort: 4500
      nodePort: 31112
